### PR TITLE
aiohttp is not actually a dependency

### PR DESCRIPTION
**Pull request by dotlambda**
and requests was removed erroneously

### CODE REVIEW

**Comment by cyberjunky** [comment]
Thanks, it was a leftover from async conversion tryout.

**Comment by cyberjunky** [comment]
Where do you use this library for if I may ask?

**Comment by dotlambda** [comment]
> Where do you use this library for if I may ask?

We packaged it in Nixpkgs as a dependency of Home Assistant. See https://github.com/NixOS/nixpkgs/pull/284893 for why I made this PR.

**Comment by cyberjunky** [comment]
I wonder, why are you building packages from unreleased and unused modules? I know there is a version 0.0.44 in the code but there is no release 0.0.44 posted yet, nor is that version used yet in the home assistant integration linked to it.

**Comment by dotlambda** [comment]
You did release 0.0.44 on PyPI: https://pypi.org/project/pyfireservicerota/
As long as the component tests pass, we're fine with using a newer version than Home Assistant.

**Comment by cyberjunky** [comment]
Understood, taken note of it, didn't know this flow was in place, thank you.

**Pull request merged**
